const Strings = {
    CLAIMS : 'claimsManagement',
    ELIGIBILITY : 'eligibilityManagement',
    EDIT_CLAIM : 'editClaim',
    TRAN_MANAGMENT : 'tranMng',
    FULL_FILE : 'full_file',
    TRAD_MANAGEMENT : 'tradMng',
    ENR_MANAGEMENT : 'enrMng',
    PROC_MANAGEMENT : 'procMng',
    REP_MANAGEMENT : 'repMng',
    ACK_MANAGEMENT : 'ackMng',

    claimsDashboard: 'claimsDashboard',
    realTime : 'realTime',
    tradingPartnerConfiguration : 'tradingPartnerConfiguration',
    claimsDashboard_835 : 'claimsDashboard_835',
    claimsDashboard_834 : 'claimsDashboard_834',
    claimsDashboard_834_details : 'claimsDashboard_834_details',
    editConfiguration : 'editConfiguration',
    realTime_276 : 'realTime_276',
    submitClaims : 'submitClaims',
    claimDetails : 'claimDetails',
    claimsAudit : 'claimsAudit',
    claimsError : 'claimsError',
    matchClaims : 'matchClaims',
    researchQueue : 'researchQueue',
    viewEdit : 'viewEdit',
    fullFile834 : 'fullFile834',
    EnrollmentError : 'Enrollment_Error', 
    EnrollmentDetails: 'EnrollmentDetails',
    EnrollmentErrors: 'EnrollmentErrors',
    Outbound_dashboard:'Outbound_dashboard',
    Eligibility_Reconcile_Search:'Eligibility_Reconcile_Search',
    Eligibility_Errors:'Eligibility_Errors',
    EligibilityErrorsDelta :'EligibilityErrorsDelta',
    HistoryEligibilityErrorsDelta: 'HistoryEligibilityErrorsDelta',
    RateCodeDelta: 'RateCodeDelta',
    PlanIntegrationEligibilityErrors: 'PlanIntegrationEligibilityErrors',
    HistoryRateCodeDelta: 'HistoryRateCodeDelta',
    CustomDBDetails: 'CustomDBDetails',
    EligibilityErrorsDuplicate: 'EligibilityErrorsDuplicate',
    OutboundDetails: 'OutboundDetails',
    FullComparsion_dashboard: 'FullComparsion_dashboard'
}

export default Strings;
